/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class SimpleNode implements Node {

    protected Node parent;
    protected Node[] children;
    protected int id;
    protected Object value;
    protected XQueryParser parser;
    public    int     m_type;
    public    String  m_text;

    public SimpleNode(int i) {
        id = i;
    }

    public SimpleNode(XQueryParser p, int i) {
        this(i);
        parser = p;
    }

    public int getId(){
        return this.id;
    }

    public void jjtOpen() {
    }

    public void jjtClose() {
    }

    public void setToken( int type, String text ){
        m_type = type; 
        m_text = text;
    }

    public String getText()  { return m_text; }
    public void jjtSetParent(Node n) { parent = n; }
    public Node jjtGetParent() { return parent; }

    public void jjtAddChild(Node n, int i) {
        if (children == null) {
            children = new Node[i + 1];
        } else if (i >= children.length) {
            Node c[] = new Node[i + 1];
            System.arraycopy(children, 0, c, 0, children.length);
            children = c;
        }
        children[i] = n;
    }

    public Node jjtGetChild(int i) {
        return children[i];
    }

    public int jjtGetNumChildren() {
        return (children == null) ? 0 : children.length;
    }
    public Object jjtAccept(XQueryParserVisitor visitor, Object data){
        return data;
    }

    public void jjtSetValue(Object value) { this.value = value; }
    public Object jjtGetValue() { return value; }

    /* You can override these two methods in subclasses of SimpleNode to
       customize the way the node appears when the tree is dumped.  If
       your output uses more than one line you should override
       toString(String), otherwise overriding toString() is probably all
       you need to do. */

    public String toString() { return XQueryParserTreeConstants.jjtNodeName[id]; }
    public String toString(String prefix) { return prefix + toString(); }

    /* Override this method if you want to customize how the node dumps
       out its children. */
    public void dump(String prefix) {
        if(this.m_text != null)
            System.out.println(toString(prefix) + ":"+this.m_text);
        else
            System.out.println(toString(prefix));
        if (children != null) {
            for (int i = 0; i < children.length; ++i) {
                SimpleNode n = (SimpleNode)children[i];
                if (n != null) {
                    String nodeText = n.getText();
                    if(nodeText != null)
                        n.dump(prefix + " " );
                    //n.dump(prefix + " " + nodeText + ":");
                    else
                        n.dump(prefix + " " );
                }
            }
        }
    }
}

/* JavaCC - OriginalChecksum=f63e377c6c9e47afc239bf8761910a36 (do not edit this line) */
