/* Generated By:JJTree: Do not edit this line. AST_FORCLAUSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_FORCLAUSE extends SimpleNode {
  public AST_FORCLAUSE(int id) {
    super(id);
  }

  public AST_FORCLAUSE(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3af8b09adf6f609757bc20e199f0504 (do not edit this line) */
