/* Generated By:JJTree: Do not edit this line. AST_COND.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_COND extends SimpleNode {
  public AST_COND(int id) {
    super(id);
  }

  public AST_COND(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1a519c9233f017c6f3942ff8c55ad62c (do not edit this line) */
