/* Generated By:JJTree: Do not edit this line. AST_RETURNCLAUSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_RETURNCLAUSE extends SimpleNode {
  public AST_RETURNCLAUSE(int id) {
    super(id);
  }

  public AST_RETURNCLAUSE(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=24339e47174bdec8b7122bd5723378ea (do not edit this line) */
