/* Generated By:JJTree: Do not edit this line. AST_F2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_F2 extends SimpleNode {
  public AST_F2(int id) {
    super(id);
  }

  public AST_F2(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d908a6b96608a369dd6cc859ae2bdc35 (do not edit this line) */
