/* Generated By:JJTree: Do not edit this line. AST_LETCLAUSEWE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_LETCLAUSEWE extends SimpleNode {
  public AST_LETCLAUSEWE(int id) {
    super(id);
  }

  public AST_LETCLAUSEWE(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2048c04d2aaa5ba22069f1966780c75c (do not edit this line) */
