/* Generated By:JJTree: Do not edit this line. AST_STRING.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_STRING extends SimpleNode {
  public AST_STRING(int id) {
    super(id);
  }

  public AST_STRING(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fd5a3f1f3171eb628ec988bb03b20e27 (do not edit this line) */
