/* Generated By:JJTree: Do not edit this line. AST_XQ.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_XQ extends SimpleNode {
  public AST_XQ(int id) {
    super(id);
  }

  public AST_XQ(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d4111c9d06079792dd4e8e8b8b9dacd (do not edit this line) */
