/* Generated By:JJTree: Do not edit this line. AST_PF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_PF extends SimpleNode {
  public AST_PF(int id) {
    super(id);
  }

  public AST_PF(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e87f182fe24115dd21451982726f9761 (do not edit this line) */
