/* Generated By:JJTree: Do not edit this line. AST_SingleSlash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_SingleSlash extends SimpleNode {
  public AST_SingleSlash(int id) {
    super(id);
  }

  public AST_SingleSlash(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=28c7e08cb2f5a23b09f8094d26e79a84 (do not edit this line) */
