/* Generated By:JJTree: Do not edit this line. AST_RP2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_RP2 extends SimpleNode {
  public AST_RP2(int id) {
    super(id);
  }

  public AST_RP2(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59acbe4794d8f398f3a8ad838161521e (do not edit this line) */
