/* Generated By:JJTree: Do not edit this line. AST_AP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_AP extends SimpleNode {
  public AST_AP(int id) {
    super(id);
  }

  public AST_AP(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a906efe602f079134becb9640f098739 (do not edit this line) */
