/* Generated By:JJTree: Do not edit this line. AST_FILENAME.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_FILENAME extends SimpleNode {
  public AST_FILENAME(int id) {
    super(id);
  }

  public AST_FILENAME(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b161493b521bd87382e3c0a8110634ef (do not edit this line) */
