/* Generated By:JJTree: Do not edit this line. AST_Root.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_Root extends SimpleNode {
  public AST_Root(int id) {
    super(id);
  }

  public AST_Root(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=056b16f378590ca86570147cdc2bec31 (do not edit this line) */
