/* Generated By:JJTree: Do not edit this line. AST_TAGNAME.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_TAGNAME extends SimpleNode {
  public AST_TAGNAME(int id) {
    super(id);
  }

  public AST_TAGNAME(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c4113d9e2fcf19fe928e1ccb4775605 (do not edit this line) */
