/* Generated By:JJTree: Do not edit this line. AST_XQ2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_XQ2 extends SimpleNode {
  public AST_XQ2(int id) {
    super(id);
  }

  public AST_XQ2(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d99802349ad0b4fba19f0440b8f13a9 (do not edit this line) */
