/* Generated By:JJTree: Do not edit this line. AST_F.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_F extends SimpleNode {
  public AST_F(int id) {
    super(id);
  }

  public AST_F(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4548183f254a8a9513fcd849067c5a02 (do not edit this line) */
