/* Generated By:JJTree: Do not edit this line. AST_VARD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_VARD extends SimpleNode {
  public AST_VARD(int id) {
    super(id);
  }

  public AST_VARD(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=93af61a4992f9c6d1d212cabf26a6dc8 (do not edit this line) */
