/* Generated By:JJTree: Do not edit this line. AST_VAR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_VAR extends SimpleNode {
  public AST_VAR(int id) {
    super(id);
  }

  public AST_VAR(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c04f38b0fdda47b70fc3b95d3170bdd (do not edit this line) */
