/* Generated By:JJTree: Do not edit this line. AST_FORCLAUSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_FORCLAUSE extends SimpleNode {
  public AST_FORCLAUSE(int id) {
    super(id);
  }

  public AST_FORCLAUSE(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b3bc5d2f18a8f6f5de572f4eff7c43be (do not edit this line) */
