/* Generated By:JJTree: Do not edit this line. AST_COND2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_COND2 extends SimpleNode {
  public AST_COND2(int id) {
    super(id);
  }

  public AST_COND2(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=100ac8b251ef47bf98cffe5002efb3db (do not edit this line) */
