/* Generated By:JJTree: Do not edit this line. AST_pf2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_pf2 extends SimpleNode {
  public AST_pf2(int id) {
    super(id);
  }

  public AST_pf2(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9aa44b9f28a6039aa3a7947938d96812 (do not edit this line) */
