/* Generated By:JJTree: Do not edit this line. AST_DoubleSlash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_DoubleSlash extends SimpleNode {
  public AST_DoubleSlash(int id) {
    super(id);
  }

  public AST_DoubleSlash(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1b748e1388cc54622e3a7efc00934f03 (do not edit this line) */
