/* Generated By:JJTree: Do not edit this line. AST_TAGNAME.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_TAGNAME extends SimpleNode {
  public AST_TAGNAME(int id) {
    super(id);
  }

  public AST_TAGNAME(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=da90ae6e3fe7178961378be9d631ff47 (do not edit this line) */
