/* Generated By:JJTree: Do not edit this line. AST_LETCLAUSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_LETCLAUSE extends SimpleNode {
  public AST_LETCLAUSE(int id) {
    super(id);
  }

  public AST_LETCLAUSE(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0740e75c4b39c61c1d73f9ece7f1de8a (do not edit this line) */
