/* Generated By:JJTree: Do not edit this line. AST_LETCLAUSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_LETCLAUSE extends SimpleNode {
  public AST_LETCLAUSE(int id) {
    super(id);
  }

  public AST_LETCLAUSE(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1ddcbe743d25f9e05774800fdf379ec5 (do not edit this line) */
