/* Generated By:JJTree: Do not edit this line. AST_RETURNCLAUSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package XQuery;

public
class AST_RETURNCLAUSE extends SimpleNode {
  public AST_RETURNCLAUSE(int id) {
    super(id);
  }

  public AST_RETURNCLAUSE(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6cdc29b255cd7b52f8b60da7d1ba9803 (do not edit this line) */
