/* Generated By:JJTree&JavaCC: Do not edit this line. XQueryParserConstants.java */
package XQuery;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 38;
  /** RegularExpression Id. */
  int FILENAME = 39;
  /** RegularExpression Id. */
  int VAR = 40;
  /** RegularExpression Id. */
  int TAGNAME = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"document(\\\"\"",
    "\"\\\")/\"",
    "\"/\"",
    "\"eq\"",
    "\"is\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"*\"",
    "\".\"",
    "\"..\"",
    "\"text()\"",
    "\"//\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\"</\"",
    "\":=\"",
    "\"in\"",
    "\"for\"",
    "\"let\"",
    "\"where\"",
    "\"return\"",
    "\"empty(\"",
    "\"some\"",
    "\"satisfies\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<STRING>",
    "<FILENAME>",
    "<VAR>",
    "<TAGNAME>",
  };

}
