/* Generated By:JJTree&JavaCC: Do not edit this line. XQueryParserConstants.java */
package XQuery;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 17;
  /** RegularExpression Id. */
  int DOC = 18;
  /** RegularExpression Id. */
  int TXT = 19;
  /** RegularExpression Id. */
  int IN = 20;
  /** RegularExpression Id. */
  int FOR = 21;
  /** RegularExpression Id. */
  int WHERE = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int IS = 25;
  /** RegularExpression Id. */
  int EMPTY = 26;
  /** RegularExpression Id. */
  int SOME = 27;
  /** RegularExpression Id. */
  int SATISFIES = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int ASSIGN = 32;
  /** RegularExpression Id. */
  int STAR = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int DOUBLEDOT = 35;
  /** RegularExpression Id. */
  int SINGLELASH = 36;
  /** RegularExpression Id. */
  int DOUBLESLASH = 37;
  /** RegularExpression Id. */
  int FILENAME = 38;
  /** RegularExpression Id. */
  int STRING = 39;
  /** RegularExpression Id. */
  int VAR = 40;
  /** RegularExpression Id. */
  int TAGNAME = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"(\\\"\"",
    "\"\\\")\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\"</\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"let\"",
    "<DOC>",
    "\"text()\"",
    "\"in\"",
    "\"for\"",
    "\"where\"",
    "\"return\"",
    "<EQ>",
    "<IS>",
    "\"empty\"",
    "\"some\"",
    "\"satisfies\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\":=\"",
    "\"*\"",
    "\".\"",
    "\"..\"",
    "\"/\"",
    "\"//\"",
    "<FILENAME>",
    "<STRING>",
    "<VAR>",
    "<TAGNAME>",
  };

}
