/* Generated By:JavaCC: Do not edit this line. XQueryParserTreeConstants.java Version 5.0 */
package XQuery;

public interface XQueryParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTAP = 1;
  public int JJTPF = 2;
  public int JJTVOID = 3;
  public int JJTRP = 4;
  public int JJTXQ = 5;
  public int JJTFORCLAUSE = 6;
  public int JJTLETCLAUSE = 7;
  public int JJTWHERECLAUSE = 8;
  public int JJTRETURNCLAUSE = 9;
  public int JJTCOND = 10;
  public int JJTFILENAME = 11;
  public int JJTVAR = 12;
  public int JJTSTRING = 13;
  public int JJTTAGNAME = 14;


  public String[] jjtNodeName = {
    "Root",
    "AP",
    "PF",
    "void",
    "RP",
    "XQ",
    "FORCLAUSE",
    "LETCLAUSE",
    "WHERECLAUSE",
    "RETURNCLAUSE",
    "COND",
    "FILENAME",
    "VAR",
    "STRING",
    "TAGNAME",
  };
}
/* JavaCC - OriginalChecksum=f0ba04aa8f87e4a314ee3b4af77312a1 (do not edit this line) */
