/* Generated By:JavaCC: Do not edit this line. XQueryParserVisitor.java Version 5.0 */
package XQuery;

public interface XQueryParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(AST_Root node, Object data);
  public Object visit(AST_AP node, Object data);
  public Object visit(AST_DoubleSlash node, Object data);
  public Object visit(AST_SingleSlash node, Object data);
  public Object visit(AST_PF node, Object data);
  public Object visit(AST_Eq node, Object data);
  public Object visit(AST_Is node, Object data);
  public Object visit(AST_Not node, Object data);
  public Object visit(AST_And node, Object data);
  public Object visit(AST_Or node, Object data);
  public Object visit(AST_RP node, Object data);
  public Object visit(AST_Star node, Object data);
  public Object visit(AST_Dot node, Object data);
  public Object visit(AST_DDot node, Object data);
  public Object visit(AST_Txt node, Object data);
  public Object visit(AST_Comma node, Object data);
  public Object visit(AST_XQ node, Object data);
  public Object visit(AST_FORCLAUSE node, Object data);
  public Object visit(AST_LETCLAUSE node, Object data);
  public Object visit(AST_WHERECLAUSE node, Object data);
  public Object visit(AST_RETURNCLAUSE node, Object data);
  public Object visit(AST_COND node, Object data);
  public Object visit(AST_Empty node, Object data);
  public Object visit(AST_Some node, Object data);
  public Object visit(AST_FILENAME node, Object data);
  public Object visit(AST_VAR node, Object data);
  public Object visit(AST_STRING node, Object data);
  public Object visit(AST_TAGNAME node, Object data);
}
/* JavaCC - OriginalChecksum=5c442f51ccaff9a4cc0d5b52fd85d819 (do not edit this line) */
