/* Generated By:JavaCC: Do not edit this line. XQueryParserTreeConstants.java Version 5.0 */
package XQuery;

public interface XQueryParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTAP = 1;
  public int JJTONESLASH = 2;
  public int JJTDOUBLESLASH = 3;
  public int JJTPF = 4;
  public int JJTVOID = 5;
  public int JJTRP = 6;
  public int JJTXQ = 7;
  public int JJTFORCLAUSE = 8;
  public int JJTLETCLAUSE = 9;
  public int JJTWHERECLAUSE = 10;
  public int JJTRETURNCLAUSE = 11;
  public int JJTCOND = 12;
  public int JJTFILENAME = 13;
  public int JJTVAR = 14;
  public int JJTSTRING = 15;
  public int JJTTAGNAME = 16;


  public String[] jjtNodeName = {
    "Root",
    "AP",
    "OneSlash",
    "DoubleSlash",
    "PF",
    "void",
    "RP",
    "XQ",
    "FORCLAUSE",
    "LETCLAUSE",
    "WHERECLAUSE",
    "RETURNCLAUSE",
    "COND",
    "FILENAME",
    "VAR",
    "STRING",
    "TAGNAME",
  };
}
/* JavaCC - OriginalChecksum=a16b5503d45a87126a9cfe8a13ef1337 (do not edit this line) */
