/* Generated By:JavaCC: Do not edit this line. XQueryParserVisitor.java Version 5.0 */
package XQuery;

public interface XQueryParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(AST_Root node, Object data);
  public Object visit(AST_AP node, Object data);
  public Object visit(AST_PF node, Object data);
  public Object visit(AST_RP node, Object data);
  public Object visit(AST_XQ node, Object data);
  public Object visit(AST_FORCLAUSE node, Object data);
  public Object visit(AST_LETCLAUSE node, Object data);
  public Object visit(AST_WHERECLAUSE node, Object data);
  public Object visit(AST_RETURNCLAUSE node, Object data);
  public Object visit(AST_COND node, Object data);
  public Object visit(AST_FILENAME node, Object data);
  public Object visit(AST_VAR node, Object data);
  public Object visit(AST_STRING node, Object data);
  public Object visit(AST_TAGNAME node, Object data);
}
/* JavaCC - OriginalChecksum=cc576c2304135fe32911221baed9b7ed (do not edit this line) */
